import React,{useState} from 'react'
import {createRoot} from 'react-dom/client'
import {LayoutDashboard, UserRound, FileText, Target, Map, MessageCircle, CheckCircle2, Upload, ArrowRight, Sparkles} from 'lucide-react'
import './styles.css'

const api=async(path,opts={})=>{const r=await fetch(path,{...opts,headers:{'Content-Type':'application/json',...(opts.headers||{})}});if(!r.ok)throw Error(await r.text());return r.json()}
const sample={name:'Alex Morgan',email:'alex@example.com',target_role:'Frontend Engineer',experience:'Mid-level',skills:['React','JavaScript','Git'],goals:'Join a product-minded team'}
function App(){
 const [tab,setTab]=useState('Overview'),[profile,setProfile]=useState(sample),[jd,setJd]=useState('We are looking for a Frontend Engineer with React, TypeScript, JavaScript, testing, and communication skills.'),[analysis,setAnalysis]=useState(null),[resume,setResume]=useState(''),[loading,setLoading]=useState(false),[done,setDone]=useState({})
 const nav=[['Overview',LayoutDashboard],['Profile',UserRound],['Resume',FileText],['Skill gaps',Target],['Roadmap',Map],['Interview',MessageCircle]]
 async function run(){setLoading(true);try{const x=await api('/api/analyze',{method:'POST',body:JSON.stringify({profile,job_description:jd,resume_text:resume})});setAnalysis(x);setTab('Overview')}catch(e){alert('Start the API first: '+e.message)}finally{setLoading(false)}}
 const toggle=(x)=>setDone({...done,[x]:!done[x]})
 return <div className="app"><aside><div className="brand"><span className="logo"><Sparkles size={18}/></span><span>Career<span className="accent">Pilot</span></span></div><div className="workspace">MY WORKSPACE</div>{nav.map(([n,I])=><button className={tab===n?'nav active':'nav'} onClick={()=>setTab(n)} key={n}><I size={18}/>{n}</button>)}<div className="aside-bottom"><div className="mini-avatar">AM</div><div><b>Alex Morgan</b><small>Career switcher</small></div><span>•••</span></div></aside><main><header><div><p className="eyebrow">TUESDAY, SEPTEMBER 15, 2026</p><h1>{tab==='Overview'?'Good morning, Alex.':'Your '+tab.toLowerCase()}</h1></div><button className="avatar">AM</button></header>{tab==='Overview'&&<Overview analysis={analysis} run={run} loading={loading} setTab={setTab} jd={jd} setJd={setJd}/>} {tab==='Profile'&&<Profile profile={profile} setProfile={setProfile}/>} {tab==='Resume'&&<Resume setResume={setResume} resume={resume}/>} {tab==='Skill gaps'&&<Gaps analysis={analysis}/>} {tab==='Roadmap'&&<Roadmap analysis={analysis} done={done} toggle={toggle}/>} {tab==='Interview'&&<Interview role={profile.target_role}/>} </main></div>
}
function Card({children,className=''}){return <section className={'card '+className}>{children}</section>}
function Overview({analysis,run,loading,setTab,jd,setJd}){return <><div className="hero"><div><span className="pill"><Sparkles size={14}/> AI-powered career plan</span><h2>Turn your next career move<br/>into a <i>clear plan.</i></h2><p>Get a personalized read on your readiness, discover what to learn next, and practice with confidence.</p><button className="primary" onClick={run}>{loading?'Analyzing…':'Analyze my fit'} <ArrowRight size={17}/></button></div><div className="hero-art"><div className="orbit o1"></div><div className="orbit o2"></div><div className="orbit o3"></div><div className="planet">✦</div></div></div><Card className="job-card"><div className="card-title"><div><small>JOB DESCRIPTION</small><h2>What role are you targeting?</h2></div><Target/></div><textarea value={jd} onChange={e=>setJd(e.target.value)} placeholder="Paste a job description here…"/></Card><div className="section-head"><h3>Your snapshot</h3><button className="link" onClick={()=>setTab('Skill gaps')}>View full analysis <ArrowRight size={15}/></button></div><div className="grid3"><Card><small>READINESS SCORE</small><div className="score">{analysis?.match_score||68}<span>%</span></div><div className="bar"><b style={{width:(analysis?.match_score||68)+'%'}}/></div><p className="muted">{analysis?'Based on your latest analysis':'Run an analysis to personalize this score'}</p></Card><Card><small>TOP FOCUS</small><h3 className="focus">{analysis?.gaps?.[0]?.skill||'TypeScript'}</h3><p className="muted">{analysis?.gaps?.[0]?.reason||'A high-impact skill to strengthen for your target role.'}</p><button className="text-btn" onClick={()=>setTab('Skill gaps')}>Explore gaps <ArrowRight size={14}/></button></Card><Card><small>WEEKLY STREAK</small><div className="streak">4 <span>days</span></div><p className="muted">Keep the momentum going.</p><div className="dots">● ● ● ● <span>● ● ●</span></div></Card></div></>}
function Profile({profile,setProfile}){return <Card><div className="card-title"><div><small>YOUR PROFILE</small><h2>Tell us about yourself</h2></div><UserRound/></div><div className="form-grid">{[['name','Full name'],['email','Email'],['target_role','Target role'],['experience','Experience level']].map(([k,l])=><label>{l}<input value={profile[k]} onChange={e=>setProfile({...profile,[k]:e.target.value})}/></label>)}</div><label>Skills <input value={profile.skills.join(', ')} onChange={e=>setProfile({...profile,skills:e.target.value.split(',').map(x=>x.trim())})}/></label><label>Career goal <textarea value={profile.goals} onChange={e=>setProfile({...profile,goals:e.target.value})}/></label><button className="primary">Save profile <CheckCircle2 size={16}/></button></Card>}
function Resume({setResume,resume}){return <Card><div className="card-title"><div><small>RESUME LAB</small><h2>Bring your experience to life</h2><p className="muted">Paste your resume text or upload a .txt file for local analysis.</p></div><FileText/></div><label className="upload"><Upload size={25}/><b>Drop your resume here</b><span>TXT supported in this MVP</span><input type="file" accept=".txt" onChange={e=>{const f=e.target.files?.[0];if(f){const r=new FileReader();r.onload=()=>setResume(r.result);r.readAsText(f)}}}/></label><textarea className="resume-box" placeholder="Or paste resume text here…" value={resume} onChange={e=>setResume(e.target.value)}/></Card>}
function Gaps({analysis}){return <Card><div className="card-title"><div><small>PERSONALIZED ANALYSIS</small><h2>Close your skill gaps</h2><p className="muted">Prioritized by impact on your target role.</p></div><Target/></div>{(analysis?.gaps||[{skill:'TypeScript',priority:'High',reason:'Common requirement for modern frontend teams.',action:'Build a typed component and API model.'},{skill:'Testing',priority:'Medium',reason:'Testing evidence improves interview confidence.',action:'Add unit tests to a portfolio project.'}]).map((g,i)=><div className="gap"><div className={'priority '+g.priority.toLowerCase()}>{g.priority}</div><div className="gap-main"><h3>{g.skill}</h3><p>{g.reason}</p><small>Next step · {g.action}</small></div><div className="gap-score">{g.score||72}%</div></div>)}</Card>}
function Roadmap({analysis,done,toggle}){return <Card><div className="card-title"><div><small>4-WEEK ROADMAP</small><h2>Your next best steps</h2></div><Map/></div>{(analysis?.roadmap||[]).map(x=><div className="road"><button onClick={()=>toggle(x.title)} className={done[x.title]?'check checked':'check'}>{done[x.title]?'✓':''}</button><div><small>WEEK {x.week}</small><h3>{x.title}</h3>{x.tasks.map(t=><p>• {t}</p>)}</div></div>)}</Card>}
function Interview({role}){const [qs,setQs]=useState([]);return <Card><div className="card-title"><div><small>INTERVIEW STUDIO</small><h2>Practice with purpose</h2><p className="muted">Build calm, specific answers for your next {role} interview.</p></div><MessageCircle/></div><button className="primary" onClick={async()=>setQs((await api('/api/interview/questions',{method:'POST',body:JSON.stringify({role})})).questions)}>Generate questions <Sparkles size={16}/></button><div className="questions">{qs.map((q,i)=><div className="question"><span>0{i+1}</span><div><b>{q.question}</b><p>{q.tip}</p></div></div>)}</div></Card>}
createRoot(document.getElementById('root')).render(<App/>)
